name: ui
description: "UI"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # url사용을 위한 패키지
  url_launcher: ^6.1.10
  # icon사용을 위한 패키지
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/instagram_icon.png
    - assets/youtube_icon.png
    - assets/kakao_icon.png
    - assets/logo.png
    - assets/computer/ABKO_M2000_NOVA_ARGB_강화유리_블랙.png
    - assets/computer/ABKO_NCORE_G30_트루포스_미들타워.png
    - assets/computer/ABKO_NCORE_G30_트루포스_화이트.png

  fonts:
    - family: GmarketSans
      fonts:
        - asset: assets/fonts/GmarketSansBold.otf
          weight: 700
        - asset: assets/fonts/GmarketSansLight.otf
          weight: 300
        - asset: assets/fonts/GmarketSansMedium.otf
          weight: 500
